spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testDB
  jpa:
    hibernate:
#      ddl-auto: update
      ddl-auto: create
      properties:
        hibernate:
          default_batch_fetch_size: 1000
          open-in-view: false

logging:
  level:
    org.springframework.jdbc.core: trace
    org.hibernate.SQL: debug    # Logger
    org.hibernate.type: trace
